# Generated by Django 3.1.7 on 2022-02-23 20:51

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0002_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Ime', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
