# Generated by Django 3.1.7 on 2022-02-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0004_auto_20220223_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
