# Generated by Django 3.1.7 on 2022-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0005_auto_20220223_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
