# Generated by Django 3.1.7 on 2022-02-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0009_auto_20220223_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
