# Generated by Django 3.1.7 on 2022-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0011_auto_20220223_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='images/maja.jpg'),
        ),
    ]
