# Generated by Django 3.1.7 on 2022-02-23 22:17

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0013_auto_20220223_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='username'),
        ),
    ]
