# Generated by Django 3.1.7 on 2022-02-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0014_auto_20220223_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
