# Generated by Django 3.1.7 on 2022-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0015_auto_20220223_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
