# Generated by Django 3.1.7 on 2022-03-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0016_auto_20220301_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
    ]
