# Generated by Django 3.1.7 on 2022-03-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0018_zanr'),
    ]

    operations = [
        migrations.AddField(
            model_name='zanr',
            name='slikaZanr',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
