# Generated by Django 3.1.7 on 2022-03-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0024_citat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citat',
            name='nazivKnjige',
        ),
        migrations.AddField(
            model_name='knjiga',
            name='citat',
            field=models.ManyToManyField(to='bookwormApp.Citat'),
        ),
    ]
