# Generated by Django 3.1.7 on 2022-03-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0025_auto_20220301_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='mesec',
            field=models.CharField(choices=[('JANUAR', 'Januar'), ('FEBRUAR', 'Februar'), ('MART', 'Mart'), ('APRIL', 'April'), ('MAJ', 'Maj'), ('JUN', 'Jun'), ('JUL', 'Jul'), ('AVGUST', 'Avgust'), ('SEPTEMABR', 'Septembar'), ('OKTOBAR', 'Oktobar'), ('NOVEMBAR', 'Novembar'), ('DECEMBAR', 'Decembar')], default='Januar', max_length=12),
        ),
        migrations.AlterField(
            model_name='knjiga',
            name='ocena',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 1.5), (3, 2), (4, 2.5), (5, 3), (6, 3.5), (7, 4), (8, 4.5), (9, 5)], default=1),
        ),
    ]
