# Generated by Django 3.1.7 on 2022-03-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0026_auto_20220301_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='zanr',
            name='icon',
            field=models.ImageField(blank=True, max_length=800, upload_to=''),
        ),
    ]
