# Generated by Django 3.1.7 on 2022-03-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0027_zanr_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='mesec',
            field=models.CharField(choices=[('Januar', 'JANUAR'), ('Februar', 'FEBRUAR'), ('Mart', 'MART'), ('April', 'APRIL'), ('Maj', 'MAJ'), ('Jun', 'JUN'), ('Jul', 'JUL'), ('Avgust', 'AVGUST'), ('Septembar', 'SEPTEMABR'), ('Oktobar', 'OKTOBAR'), ('Novembar', 'NOVEMBAR'), ('Decembar', 'DECEMBAR')], default='Januar', max_length=12),
        ),
        migrations.AlterField(
            model_name='knjiga',
            name='ocena',
            field=models.IntegerField(blank=True, choices=[(1, 1), (1.5, 2), (2, 3), (2.5, 4), (3, 5), (3.5, 6), (4, 7), (4.5, 8), (5, 9)], default=1),
        ),
    ]
