# Generated by Django 3.1.7 on 2022-03-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0028_auto_20220302_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='citat',
            field=models.ManyToManyField(blank=True, to='bookwormApp.Citat'),
        ),
    ]
