# Generated by Django 3.1.7 on 2022-03-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0029_auto_20220305_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knjiga',
            name='citat',
        ),
        migrations.AddField(
            model_name='citat',
            name='nazivKnjige',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookwormApp.knjiga'),
        ),
    ]
