# Generated by Django 3.1.7 on 2022-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0030_auto_20220305_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='mesec',
            field=models.CharField(blank=True, choices=[('Januar', 'JANUAR'), ('Februar', 'FEBRUAR'), ('Mart', 'MART'), ('April', 'APRIL'), ('Maj', 'MAJ'), ('Jun', 'JUN'), ('Jul', 'JUL'), ('Avgust', 'AVGUST'), ('Septembar', 'SEPTEMABR'), ('Oktobar', 'OKTOBAR'), ('Novembar', 'NOVEMBAR'), ('Decembar', 'DECEMBAR')], default='Januar', max_length=12),
        ),
    ]
