# Generated by Django 3.1.7 on 2022-03-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0033_auto_20220305_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='knjiga',
            name='kupljeno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knjiga',
            name='procitano',
            field=models.BooleanField(default=False),
        ),
    ]
