# Generated by Django 3.1.7 on 2022-03-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0034_auto_20220305_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='ocena',
            field=models.FloatField(blank=True, choices=[(1, 1), (1.5, 2), (2, 3), (2.5, 4), (3, 5), (3.5, 6), (4, 7), (4.5, 8), (5, 9)], null=True),
        ),
    ]
