# Generated by Django 3.1.7 on 2022-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwormApp', '0036_auto_20220328_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knjiga',
            name='ocena',
            field=models.DecimalField(blank=True, choices=[(1, 1), (1.5, 2), (2, 3), (2.5, 4), (3, 5), (3.5, 6), (4, 7), (4.5, 8), (5, 9)], decimal_places=2, max_digits=30, null=True),
        ),
    ]
